void 18987_SUM.csv_SynRadAna.root()
{
//=========Macro generated from canvas: Check/Check
//=========  (Thu May 28 12:11:57 2020) by ROOT version 6.16/00
   TCanvas *Check = new TCanvas("Check", "Check",0,0,1000,1000);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   Check->SetHighLightColor(2);
   Check->Range(0,0,1,1);
   Check->SetFillColor(0);
   Check->SetBorderMode(0);
   Check->SetBorderSize(2);
   Check->SetTickx(1);
   Check->SetTicky(1);
   Check->SetLeftMargin(0.16);
   Check->SetRightMargin(0.05);
   Check->SetTopMargin(0.05);
   Check->SetBottomMargin(0.16);
   Check->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Check_1
   TPad *Check_1 = new TPad("Check_1", "Check_1",0.01,0.51,0.49,0.99);
   Check_1->Draw();
   Check_1->cd();
   Check_1->Range(-1.525316,2.852615,11.13291,20.63962);
   Check_1->SetFillColor(0);
   Check_1->SetBorderMode(0);
   Check_1->SetBorderSize(2);
   Check_1->SetLogy();
   Check_1->SetTickx(1);
   Check_1->SetTicky(1);
   Check_1->SetLeftMargin(0.16);
   Check_1->SetRightMargin(0.05);
   Check_1->SetTopMargin(0.05);
   Check_1->SetBottomMargin(0.16);
   Check_1->SetFrameBorderMode(0);
   Check_1->SetFrameBorderMode(0);
   
   TH1D *h_SynRadAna_Normalization__5 = new TH1D("h_SynRadAna_Normalization__5","h_SynRadAna_ Normalization",10,0.5,10.5);
   h_SynRadAna_Normalization__5->SetBinContent(1,1000000);
   h_SynRadAna_Normalization__5->SetBinContent(2,1000000);
   h_SynRadAna_Normalization__5->SetBinContent(3,2.965931e+19);
   h_SynRadAna_Normalization__5->SetBinContent(4,1330818);
   h_SynRadAna_Normalization__5->SetBinContent(5,1000000);
   h_SynRadAna_Normalization__5->SetBinContent(6,1330818);
   h_SynRadAna_Normalization__5->SetBinError(1,1000);
   h_SynRadAna_Normalization__5->SetBinError(2,1000);
   h_SynRadAna_Normalization__5->SetBinError(3,3.807564e+16);
   h_SynRadAna_Normalization__5->SetBinError(4,1411.543);
   h_SynRadAna_Normalization__5->SetBinError(5,1000);
   h_SynRadAna_Normalization__5->SetBinError(6,1411.543);
   h_SynRadAna_Normalization__5->SetEntries(6000000);
   h_SynRadAna_Normalization__5->SetLineWidth(2);
   h_SynRadAna_Normalization__5->SetMarkerStyle(20);
   h_SynRadAna_Normalization__5->SetMarkerSize(1.2);
   h_SynRadAna_Normalization__5->GetXaxis()->SetTitle("Items");
   h_SynRadAna_Normalization__5->GetXaxis()->SetBinLabel(1,"Event");
   h_SynRadAna_Normalization__5->GetXaxis()->SetBinLabel(2,"Photon");
   h_SynRadAna_Normalization__5->GetXaxis()->SetBinLabel(3,"Flux");
   h_SynRadAna_Normalization__5->GetXaxis()->SetBinLabel(4,"G4Particle");
   h_SynRadAna_Normalization__5->GetXaxis()->SetBinLabel(5,"G4PrimaryParticle");
   h_SynRadAna_Normalization__5->GetXaxis()->SetBinLabel(6,"G4Vertex");
   h_SynRadAna_Normalization__5->GetXaxis()->SetBit(TAxis::kLabelsVert);
   h_SynRadAna_Normalization__5->GetXaxis()->SetLabelFont(42);
   h_SynRadAna_Normalization__5->GetXaxis()->SetLabelSize(0.05);
   h_SynRadAna_Normalization__5->GetXaxis()->SetTitleSize(0.05);
   h_SynRadAna_Normalization__5->GetXaxis()->SetTitleOffset(1.4);
   h_SynRadAna_Normalization__5->GetXaxis()->SetTitleFont(42);
   h_SynRadAna_Normalization__5->GetYaxis()->SetTitle("Count");
   h_SynRadAna_Normalization__5->GetYaxis()->SetLabelFont(42);
   h_SynRadAna_Normalization__5->GetYaxis()->SetLabelSize(0.05);
   h_SynRadAna_Normalization__5->GetYaxis()->SetTitleSize(0.05);
   h_SynRadAna_Normalization__5->GetYaxis()->SetTitleOffset(1.4);
   h_SynRadAna_Normalization__5->GetYaxis()->SetTitleFont(42);
   h_SynRadAna_Normalization__5->GetZaxis()->SetLabelFont(42);
   h_SynRadAna_Normalization__5->GetZaxis()->SetLabelSize(0.05);
   h_SynRadAna_Normalization__5->GetZaxis()->SetTitleSize(0.05);
   h_SynRadAna_Normalization__5->GetZaxis()->SetTitleOffset(1);
   h_SynRadAna_Normalization__5->GetZaxis()->SetTitleFont(42);
   h_SynRadAna_Normalization__5->Draw("");
   Check_1->Modified();
   Check->cd();
  
// ------------>Primitives in pad: Check_2
   TPad *Check_2 = new TPad("Check_2", "Check_2",0.51,0.51,0.99,0.99);
   Check_2->Draw();
   Check_2->cd();
   Check_2->Range(-4.651899,7.753121,21.29747,15.85108);
   Check_2->SetFillColor(0);
   Check_2->SetBorderMode(0);
   Check_2->SetBorderSize(2);
   Check_2->SetLogy();
   Check_2->SetTickx(1);
   Check_2->SetTicky(1);
   Check_2->SetLeftMargin(0.16);
   Check_2->SetRightMargin(0.05);
   Check_2->SetTopMargin(0.05);
   Check_2->SetBottomMargin(0.16);
   Check_2->SetFrameBorderMode(0);
   Check_2->SetFrameBorderMode(0);
   
   TH1D *h_SynRadAna_photonEnergy_flux__6 = new TH1D("h_SynRadAna_photonEnergy_flux__6","Source photon",200,0,100);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(1,1.47248e+15);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(2,1.137895e+14);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(3,1.449529e+13);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(4,1.036514e+13);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(5,4.088552e+12);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(6,1.927789e+12);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(7,1.006394e+12);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(8,6.283681e+11);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(9,3.515189e+11);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(10,2.552745e+11);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(11,1.375245e+11);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(12,3.14184e+11);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(13,9.490976e+10);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(14,3.272751e+10);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(16,3.272754e+09);
   h_SynRadAna_photonEnergy_flux__6->SetBinContent(17,2.945475e+10);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(1,1.982855e+12);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(2,5.508588e+11);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(3,1.961632e+11);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(4,1.666628e+11);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(5,1.051681e+11);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(6,7.200922e+10);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(7,5.069368e+10);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(8,4.087664e+10);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(9,2.986489e+10);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(10,2.646682e+10);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(11,1.885981e+10);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(12,2.956364e+10);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(13,1.619929e+10);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(14,9.37173e+09);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(16,1.034936e+09);
   h_SynRadAna_photonEnergy_flux__6->SetBinError(17,9.31441e+09);
   h_SynRadAna_photonEnergy_flux__6->SetEntries(606775);
   h_SynRadAna_photonEnergy_flux__6->SetLineWidth(2);
   h_SynRadAna_photonEnergy_flux__6->SetMarkerStyle(20);
   h_SynRadAna_photonEnergy_flux__6->SetMarkerSize(1.2);
   h_SynRadAna_photonEnergy_flux__6->GetXaxis()->SetTitle("Photon energy [keV]");
   h_SynRadAna_photonEnergy_flux__6->GetXaxis()->SetRange(0,40);
   h_SynRadAna_photonEnergy_flux__6->GetXaxis()->SetLabelFont(42);
   h_SynRadAna_photonEnergy_flux__6->GetXaxis()->SetLabelSize(0.05);
   h_SynRadAna_photonEnergy_flux__6->GetXaxis()->SetTitleSize(0.05);
   h_SynRadAna_photonEnergy_flux__6->GetXaxis()->SetTitleOffset(1.4);
   h_SynRadAna_photonEnergy_flux__6->GetXaxis()->SetTitleFont(42);
   h_SynRadAna_photonEnergy_flux__6->GetYaxis()->SetLabelFont(42);
   h_SynRadAna_photonEnergy_flux__6->GetYaxis()->SetLabelSize(0.05);
   h_SynRadAna_photonEnergy_flux__6->GetYaxis()->SetTitleSize(0.05);
   h_SynRadAna_photonEnergy_flux__6->GetYaxis()->SetTitleOffset(1.4);
   h_SynRadAna_photonEnergy_flux__6->GetYaxis()->SetTitleFont(42);
   h_SynRadAna_photonEnergy_flux__6->GetZaxis()->SetLabelFont(42);
   h_SynRadAna_photonEnergy_flux__6->GetZaxis()->SetLabelSize(0.05);
   h_SynRadAna_photonEnergy_flux__6->GetZaxis()->SetTitleSize(0.05);
   h_SynRadAna_photonEnergy_flux__6->GetZaxis()->SetTitleOffset(1);
   h_SynRadAna_photonEnergy_flux__6->GetZaxis()->SetTitleFont(42);
   h_SynRadAna_photonEnergy_flux__6->Draw("");
   Check_2->Modified();
   Check->cd();
  
// ------------>Primitives in pad: Check_3
   TPad *Check_3 = new TPad("Check_3", "Check_3",0.01,0.01,0.49,0.49);
   Check_3->Draw();
   Check_3->cd();
   Check_3->Range(-4.753164,14.79052,21.82911,15.52431);
   Check_3->SetFillColor(0);
   Check_3->SetBorderMode(0);
   Check_3->SetBorderSize(2);
   Check_3->SetLogy();
   Check_3->SetTickx(1);
   Check_3->SetTicky(1);
   Check_3->SetLeftMargin(0.16);
   Check_3->SetRightMargin(0.05);
   Check_3->SetTopMargin(0.05);
   Check_3->SetBottomMargin(0.16);
   Check_3->SetFrameBorderMode(0);
   Check_3->SetFrameBorderMode(0);
   
   TH1D *h_SynRadAna_MVTXHit_nHit_flux__7 = new TH1D("h_SynRadAna_MVTXHit_nHit_flux__7","Hit sum",2000,-0.5,1999.5);
   h_SynRadAna_MVTXHit_nHit_flux__7->SetBinContent(1,1.62e+15);
   h_SynRadAna_MVTXHit_nHit_flux__7->SetBinError(1,2.079702e+12);
   h_SynRadAna_MVTXHit_nHit_flux__7->SetEntries(606775);
   h_SynRadAna_MVTXHit_nHit_flux__7->SetLineWidth(2);
   h_SynRadAna_MVTXHit_nHit_flux__7->SetMarkerStyle(20);
   h_SynRadAna_MVTXHit_nHit_flux__7->SetMarkerSize(1.2);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetXaxis()->SetTitle("Sum number of hits");
   h_SynRadAna_MVTXHit_nHit_flux__7->GetXaxis()->SetRange(1,21);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetXaxis()->SetLabelFont(42);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetXaxis()->SetLabelSize(0.05);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetXaxis()->SetTitleSize(0.05);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetXaxis()->SetTitleOffset(1.4);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetXaxis()->SetTitleFont(42);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetYaxis()->SetLabelFont(42);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetYaxis()->SetLabelSize(0.05);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetYaxis()->SetTitleSize(0.05);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetYaxis()->SetTitleOffset(1.4);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetYaxis()->SetTitleFont(42);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetZaxis()->SetLabelFont(42);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetZaxis()->SetLabelSize(0.05);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetZaxis()->SetTitleSize(0.05);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetZaxis()->SetTitleOffset(1);
   h_SynRadAna_MVTXHit_nHit_flux__7->GetZaxis()->SetTitleFont(42);
   h_SynRadAna_MVTXHit_nHit_flux__7->Draw("");
   Check_3->Modified();
   Check->cd();
  
// ------------>Primitives in pad: Check_4
   TPad *Check_4 = new TPad("Check_4", "Check_4",0.51,0.01,0.99,0.49);
   Check_4->Draw();
   Check_4->cd();
   Check_4->Range(-4.753164,14.79052,21.82911,15.52431);
   Check_4->SetFillColor(0);
   Check_4->SetBorderMode(0);
   Check_4->SetBorderSize(2);
   Check_4->SetLogy();
   Check_4->SetTickx(1);
   Check_4->SetTicky(1);
   Check_4->SetLeftMargin(0.16);
   Check_4->SetRightMargin(0.05);
   Check_4->SetTopMargin(0.05);
   Check_4->SetBottomMargin(0.16);
   Check_4->SetFrameBorderMode(0);
   Check_4->SetFrameBorderMode(0);
   
   TH1D *h_SynRadAna_MVTX_nHit_flux__8 = new TH1D("h_SynRadAna_MVTX_nHit_flux__8","Hit sum",2000,-0.5,1999.5);
   h_SynRadAna_MVTX_nHit_flux__8->SetBinContent(1,1.62e+15);
   h_SynRadAna_MVTX_nHit_flux__8->SetBinError(1,2.079702e+12);
   h_SynRadAna_MVTX_nHit_flux__8->SetEntries(606775);
   h_SynRadAna_MVTX_nHit_flux__8->SetLineWidth(2);
   h_SynRadAna_MVTX_nHit_flux__8->SetMarkerStyle(20);
   h_SynRadAna_MVTX_nHit_flux__8->SetMarkerSize(1.2);
   h_SynRadAna_MVTX_nHit_flux__8->GetXaxis()->SetTitle("Sum number of hits");
   h_SynRadAna_MVTX_nHit_flux__8->GetXaxis()->SetRange(1,21);
   h_SynRadAna_MVTX_nHit_flux__8->GetXaxis()->SetLabelFont(42);
   h_SynRadAna_MVTX_nHit_flux__8->GetXaxis()->SetLabelSize(0.05);
   h_SynRadAna_MVTX_nHit_flux__8->GetXaxis()->SetTitleSize(0.05);
   h_SynRadAna_MVTX_nHit_flux__8->GetXaxis()->SetTitleOffset(1.4);
   h_SynRadAna_MVTX_nHit_flux__8->GetXaxis()->SetTitleFont(42);
   h_SynRadAna_MVTX_nHit_flux__8->GetYaxis()->SetLabelFont(42);
   h_SynRadAna_MVTX_nHit_flux__8->GetYaxis()->SetLabelSize(0.05);
   h_SynRadAna_MVTX_nHit_flux__8->GetYaxis()->SetTitleSize(0.05);
   h_SynRadAna_MVTX_nHit_flux__8->GetYaxis()->SetTitleOffset(1.4);
   h_SynRadAna_MVTX_nHit_flux__8->GetYaxis()->SetTitleFont(42);
   h_SynRadAna_MVTX_nHit_flux__8->GetZaxis()->SetLabelFont(42);
   h_SynRadAna_MVTX_nHit_flux__8->GetZaxis()->SetLabelSize(0.05);
   h_SynRadAna_MVTX_nHit_flux__8->GetZaxis()->SetTitleSize(0.05);
   h_SynRadAna_MVTX_nHit_flux__8->GetZaxis()->SetTitleOffset(1);
   h_SynRadAna_MVTX_nHit_flux__8->GetZaxis()->SetTitleFont(42);
   h_SynRadAna_MVTX_nHit_flux__8->Draw("");
   Check_4->Modified();
   Check->cd();
   Check->Modified();
   Check->cd();
   Check->SetSelected(Check);
}
